### PR TITLE
#314 Allow restx-common maven packaging with JDK 11

### LINKED ISSUE #314: restx-common compatibility with Java 11
*Jdk version*: java-11-openjdk-11.0.6.10-0.fc31.x86_64
*Maven version*: Maven plugin of Intellij Idea 2020.1 located in <idea_path>/plugins/maven/lib/maven3 -> Maven 3.6.1 (core)

**Stepts to reproduce:**
1. Checkout master branch (current commit: c92e983)
2. Perform a mvn verify on `restx-common`

**Expected behaviour:**
Dependencies are downloaded, application is packaged, tests are launched

**Current behaviour:**
Build fail for module `restx-common`

### PR DESCRIPTION
**Pull request by nhumblot**
Fix #314

### CODE REVIEW

**Comment by fcamblor** [comment]
@nhumblot seems like you hit https://issues.apache.org/jira/browse/MJAVADOC-580

Did you try upgrading to maven-javadoc-plugin@3.1.0 (or greater) ?

I guess this may fix the issue in a more beautiful way (avoiding maven profile for detecting javadoc path)

**Comment by fcamblor** [comment]
forget, the issue seems unrelated (got caught by issue title :-) )

**Comment by fcamblor** [comment]
I guess that your solution source was https://stackoverflow.com/questions/57081473/how-to-make-maven-javadoc-plugin-work-with-any-java-version, correct ?

**Comment by fcamblor** [comment]
FYI, simply upgrading to latest maven-javadoc-plugin (`3.2.0`) made the `mvn verify` pass with jdk11 on `restx-common` (I've got another error, but later in the build, on `restx-factory` module and it seems unrelated)

**Comment by nhumblot** [comment]
Hi @fcamblor,

Thank you for the heads up. I've taken your comments into account and opened #320. Feel free to provide other comments in this PR if you still have some.

**Pull request merged**
