### PR TITLE
TypeReference and utility methods

### PR DESCRIPTION
**Pull request by a-peyrard**
This PR introduces `TypeReference` an abstract class permitting to construct `ParameterizedType` like that:
```java
new TypeReference<List<String>>() {}.getType();
```

In `Types` class two new methods have been implemented:
- `getRawType` permit to extract a `Class` which is the raw type of a `Type`.
- `isAssignableFrom` permit to know if a type is assignable from another type, like `Class.isAssignableFrom` is doing with classes.

### CODE REVIEW

**Comment by xhanin** [comment]
Good for me.

**Comment by fcamblor** [comment]
Seems great ! :-)

I would maybe just rename a bit some types in `TypesTest ` to make tests a bit clearer.

I would suggest something like `*TypedImpl` => `*StringTypedImpl`

**Comment by a-peyrard** [comment]
Ok I tried, don't know if it's really better though. I'm not a good name finder :)

If it's ok, I will merge that tonight.

**Comment by fcamblor** [comment]
Great !

Will rebase --onto it my feature branch for #146 once merged :)

**Pull request merged**
