### PR TITLE
Better cold classes management

### PR DESCRIPTION
**Pull request by a-peyrard**
This PR permits to manage several new things about cold classes.

- It permits to add inherited classes of cold components (components being loaded in the main factory, such as `AutoStartable` ones) in cold classes list.
- It adds a way to declare cold classes using a property: `restx.cold.classes`. The property value is a list of fqcn separated by `:`.
- It adds a way to declare cold classes using a resource file: `META-INF/cold-classes.list`. Resources will be loaded from the classloader, and every classes listed will be added to the cold classes list. The file must contains a list of fqcn, one per line.
- It provides a way to fulfil the resource file using an annotation: `@Cold`. So every classes annotated with `@Cold` will be added to the resource file (thanks to a new annotation processor).

### CODE REVIEW

**Comment by xhanin** [comment]
Sounds good to me. One question: is there any reason you use `:` as separator? I usually prefer using a comma to list values (when it's not conflicting with the values), I think it's more readable, especially if you trim the values you can have a very readable list.

**Comment by a-peyrard** [comment]
No reason, I just use to much ux systems :)

So I will change to `,` soon.

**Comment by a-peyrard** [comment]
Separator changed, if it's okay for you I will merge this tomorrow.

**Comment by xhanin** [comment]
Fine for me

**Comment by fcamblor** [comment]
:+1: with some delay (sorry)

**Comment by a-peyrard** [comment]
I changed the trim according to Xavier's remark (thanks to "push -f" :)).

**Comment by fcamblor** [comment]
@a-peyrard Just 1 simple question about `@Cold` annotation : will it work on only `@Component`-annotated classes or will it work under all circumstances ?

I'm facing some weird classloader issue and tried to fix it with `@Cold` annotation but it didn't worked (my classloader issue concerns a "standard" class, not a `@Component`)

**Comment by a-peyrard** [comment]
I just checked the code, and it should work for any classes, not only
@Component. If you set the log level to "debug" for
`RestxMainRouterFactory` it should log the cold classes like this: "cold
classes: ..."

If it's not working you can try to add the property "restx.cold.classes" to
your JVM options, the value is a list of FQCN separated by commas.

**Comment by fcamblor** [comment]
Yep, tried with the `restx.cold.classes` property as well and it didn't worked for my particular case

But no worries, my problem may not be related to hot reload (I only tried to fix it with cold classes but it didn't helped)

**Comment by xhanin** [comment]
Fred, I think it would be interesting to diagnose your issue more closely to see if it's not a problem with the new cold classes approach. I will try to check that with you next week or more probably the week after, since I won't be at the office next week.

**Comment by fcamblor** [comment]
I just created [this repo](git@github.com:fcamblor/restx-cold-classes-reload.git) reproducing my case (needs current restx version to compile well as it requires `@Cold` annotation)

if you run `AppServer` from it in `dev` mode, and go to `http://127.0.0.1:8080/api/servletRootRealPath`, you will see you have a null path returned whereas the `ContainerListener` has been initialized (and the `App` enum singleton initialized as well)

If you retry it in `prod` mode, everything will go well.

**Comment by a-peyrard** [comment]
I just cloned your repo, and I will try to explain what I understood.

The App.class is loaded a first time by the main classloader (being AppClassLoader), and after that the `RestxMainRouterFactory` initialize and create a first HotCompile classloader. Unfortunately this is this first HotCompile classloader which is used to load cold classes.
Then the request is made, and another HotReload classloader is created for the request. It finds the cold class (App), but the one loaded in the first HotReload classloader.

I manage to make it work by commenting the line:
```
mainFactoryClassLoader = hotReloadingClassLoader;
```    
I don't know why I used this classloader to load the cold classes, I don't know what would be the impact, to use the original classloader instead of the one creating the main restx factory. 

HTH

**Pull request merged**
