### PR TITLE
Refactor maven project

### LINKED ISSUE #224: Update Guava to 18.0
See release notes: https://github.com/google/guava/wiki/Release18

Actually this is causing a conflict in my elasticsearch project when using elasticsearch 2.0 (which does not shade anymore 3rd party libs) and RestX.

### PR DESCRIPTION
**Pull request by dadoonet**
This commit refactors all maven `pom.xml` files so it will be easier to update 3rd party libs.

### CODE REVIEW

**Comment by dadoonet** [comment]
Hold on. Actually, I just saw that guava is used in multiple sub modules. So I need to add a commit.

BTW, I think it would be better to define in parent pom a `<dependencyManagement>` section so we don't have to repeat ourselves. WDYT?

**Comment by dadoonet** [comment]
PR updated and still:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:05 min
[INFO] Finished at: 2015-10-28T09:40:56+01:00
[INFO] Final Memory: 84M/770M
[INFO] ------------------------------------------------------------------------
```

:)

**Comment by dadoonet** [comment]
I added another commit to update jackson as well (see #226).

Note that I had to adapt some tests and I'm unsure if it's valid or not. So please review :)

**Comment by fcamblor** [comment]
Hi David :)

You have my :+1: for guava and the `dependencyManagement` section

For Jackson, I'm unsure, like you, if this is the tests the problem, or a backward incompat introduced by jackson.
I think we need some time to investigate this point (and have @xhanin review area about `PolymorphicResource` & JSON diffs)

Maybe could you split this PR in 2 :
- 1 PR for guava + `dependencyManagement` (which should be merged quickly I guess)
- 1 PR for jackson (which should take some more time to be taken into consideration)

WDYT ?

**Comment by dadoonet** [comment]
agreed. Will update this PR to focus only on guava and send another PR for jackson.

**Comment by dadoonet** [comment]
BTW @fcamblor about dependencyManagement, we have two ways for solving that:

* using maven `<dependencyManagement>` tag
* defining versions as properties as it is today, but in parent pom.

Thoughts?

**Comment by fcamblor** [comment]
Also, while rebasing, could you add a `[breaking]` tag into your guava migration commit message ?
By reading the release note, it seems a few methods have been removed (see [common.io](https://github.com/google/guava/wiki/Release18#commonio) section) and putting the `[breaking]` tag on the commit message will bring a focus on this change in our 0.35 release note :-)

**Comment by fcamblor** [comment]
About `dependencyManagement`, both ways provide their added value :
- Using `dependencyManagement` is, to my POV, the "good maven way" of doing this
- However, adding property for this allows to ensure we use the same versions amongst every jackson libs quickly when we upgrade

So I would use both ways :-)

**Comment by dadoonet** [comment]
:p

**Comment by dadoonet** [comment]
Updated

**Comment by dadoonet** [comment]
@fcamblor I pushed 177e7ecab29c32c382929f9911e91f4789875fcb

**Comment by dadoonet** [comment]
Updated, Squashed and pushed.

BTW I wonder if we should not have 2 PRs instead of a single one here?

**Comment by fcamblor** [comment]
I agree with you about a separate PR about "maven project refactoring"

I would :
- Keep current PR and renaming it to the "maven project refactoring"
- Remove 7fa8fcc from current PR .. and cherry-pick it in another PR starting from the end of current PR #225 (this PR would change only the `<guava.version>` property in parent POM :-))
- If you can amend your 7fa8fcc git comment in this new PR, it would be very nice as per my previous message :

> Also, while rebasing, could you add a [breaking] tag into your guava migration commit message ?
> By reading the release note, it seems a few methods have been removed (see common.io section) and putting the [breaking] tag on the commit message will bring a focus on this change in our 0.35 release note :-)

- You could then rebase your #228 after commits in PR #225 once merged :)

**Comment by a-peyrard** [comment]
+1 for the separation of PRs, and as @fcamblor was saying the migration to guava 18 PR will be just one line of code.
I agree with the "breaking" word in guava 18 PR comment. And I guess it will not be a problem for anyone, as removed methods from guava 17 to guava 18 were already deprecated since guava 15 (see https://code.google.com/p/guava-libraries/wiki/Release18). The most breaking thing might be coming from "common.base" though: 
"Methods in Objects which do not have equivalents in java.util.Objects have been moved to MoreObjects" (for me it will be a good thing, as I always forgot the new helper methods brought be jse7 in `java.util.Objects` ;))

**Comment by dadoonet** [comment]
Ok. So this PR is now only about maven refactoring.
#231 has been added for Guava update to 18.0
Will also rebase #226 on #231 as I guess we will merge Guava first!

Let me know if it's ok now.

**Comment by fcamblor** [comment]
Just brought back my concerns I had on 8cd8a6444f02428d01eb5de5102aae76211c9384 (I think some are important to take into consideration)

**Comment by dadoonet** [comment]
I added a new commit so it will be easier to track the changes. Let me know if I can squash them.

**Comment by fcamblor** [comment]
It's ok for me, you can squash and I'll merge the commit(s)

It may be interesting to bring the `provided` scope on `restx-server-tomcat` & `restx-server-jetty` into a separate commit (no need to create a dedicated PR for that IMHO) in order to have only a "refactoring only" commit (=just reorganizing things without changing anything) and an "improvement commit" for provided scope.

**Comment by dadoonet** [comment]
Done.

I think we should also change `<name>` in every `pom.xml` to have something more user readable when you build the project or if you think to use maven changes plugin for announcements.

For now names are:

```
[INFO] restx-parent ....................................... SUCCESS [  0.307 s]
[INFO] restx-common ....................................... SUCCESS [  0.097 s]
[INFO] restx-factory ...................................... SUCCESS [  0.096 s]
[INFO] restx-factory-testing .............................. SUCCESS [  0.059 s]
[INFO] restx-barbarywatch ................................. SUCCESS [  0.038 s]
[INFO] restx-classloader .................................. SUCCESS [  0.033 s]
[INFO] restx-apidocs-doclet ............................... SUCCESS [  0.016 s]
[INFO] restx-core ......................................... SUCCESS [  0.220 s]
[INFO] restx-core-annotation-processor .................... SUCCESS [  0.033 s]
[INFO] restx-security-basic ............................... SUCCESS [  0.054 s]
[INFO] restx-build ........................................ SUCCESS [  0.040 s]
[INFO] restx-shell ........................................ SUCCESS [  0.032 s]
[INFO] restx-shell-manager ................................ SUCCESS [  0.019 s]
[INFO] restx-package ...................................... SUCCESS [  0.010 s]
[INFO] restx-annotation-processors-package ................ SUCCESS [  0.014 s]
[INFO] restx-webjars ...................................... SUCCESS [  0.163 s]
[INFO] restx-admin ........................................ SUCCESS [  0.044 s]
[INFO] restx-servlet ...................................... SUCCESS [  0.018 s]
[INFO] restx-server-jetty ................................. SUCCESS [  0.029 s]
[INFO] restx-specs-tests .................................. SUCCESS [  0.073 s]
[INFO] restx-server-simple ................................ SUCCESS [  0.032 s]
[INFO] restx-i18n ......................................... SUCCESS [  0.044 s]
[INFO] restx-i18n-admin ................................... SUCCESS [  0.027 s]
[INFO] restx-apidocs ...................................... SUCCESS [  0.038 s]
[INFO] restx-monitor-codahale ............................. SUCCESS [  0.018 s]
[INFO] restx-monitor-admin ................................ SUCCESS [  0.038 s]
[INFO] restx-factory-admin ................................ SUCCESS [  0.021 s]
[INFO] restx-stats-admin .................................. SUCCESS [  0.058 s]
[INFO] restx-log-admin .................................... SUCCESS [  0.051 s]
[INFO] restx-specs-admin .................................. SUCCESS [  0.058 s]
[INFO] restx-specs-server ................................. SUCCESS [  0.023 s]
[INFO] restx-jongo ........................................ SUCCESS [  0.075 s]
[INFO] restx-jongo-specs-tests ............................ SUCCESS [  0.029 s]
[INFO] restx-server-tomcat ................................ SUCCESS [  0.024 s]
[INFO] restx-server-testing ............................... SUCCESS [  0.009 s]
[INFO] restx-validation ................................... SUCCESS [  0.016 s]
[INFO] restx-samplest ..................................... SUCCESS [  0.173 s]
[INFO] restx-core-shell ................................... SUCCESS [  0.044 s]
[INFO] restx-build-shell .................................. SUCCESS [  0.022 s]
[INFO] restx-specs-shell .................................. SUCCESS [  0.017 s]
[INFO] restx-core-java8 ................................... SUCCESS [  0.017 s]
[INFO] restx-specs-tests-java8 ............................ SUCCESS [  0.016 s]
[INFO] restx-samplest-java8 ............................... SUCCESS [  0.066 s]
```

When I did the maven refactoring, I kept the `name` in every pom but we could remove them as by default `name` is the `artifactId` or change them.

For example, we could change: 

* `restx-core` to `RESTX: Core`
* `restx-server-jetty` to `RESTX: Server: Jetty`
* `restx-server-tomcat` to `RESTX: Server: Tomcat`

Or something along those lines.

Wanna me to add a new commit for that? It can come within another PR though.

**Comment by fcamblor** [comment]
Why not, but let's talk about this in another dedicated PR

That way, I'll be able to merge current PR and you will be able to rebase #231 above it (and I'll be able to merge #231 as well)

**Comment by fcamblor** [comment]
BTW thanks David for your patience ;-)

**Comment by dadoonet** [comment]
Thanks for being patient for reviewing :P

**Pull request merged**
