### PR TITLE
Update Jackson to 2.8.6

### LINKED ISSUE #226: Update Jackson to 2.8.6
Actually this is causing a conflict in my elasticsearch project when using elasticsearch 2.0 (which does not shade anymore 3rd party libs) and RestX.

### PR DESCRIPTION
**Pull request by dadoonet**
# Jackson 2.8.6

Closes #226

### CODE REVIEW

**Comment by fcamblor** [comment]
Hi David,

Could you please cherry-pick commit 72c8e10 to PR #225 please ?
That way, I'll review & merge #225 :)

**Comment by dadoonet** [comment]
@fcamblor done. Going to rebase the current PR on those changes. So you'll be able to review it and merge it hopefully later.

**Comment by dadoonet** [comment]
@fcamblor Sorry. Something went wrong. Please hold the review for now.

**Comment by dadoonet** [comment]
@fcamblor Fixed. Should be fine now.

**Comment by dadoonet** [comment]
@fcamblor Ok. It's fixed now. I think we are good:

``` 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 04:01 min
[INFO] Finished at: 2015-11-09T08:29:58+01:00
[INFO] Final Memory: 94M/779M
[INFO] ------------------------------------------------------------------------
```

**Comment by dadoonet** [comment]
I updated the current PR. Once #225 is merged only the latest commit will have to be merged. So basically you'll have to review here only 68901d4.

**Comment by dadoonet** [comment]
Wondering if this one should be marked as `[breaking]` as well?

This one needs to be rebased and merged after #225 and #231.

**Comment by dadoonet** [comment]
PR rebased on master. Ready for review... :D

**Comment by dadoonet** [comment]
Ping?

**Comment by dadoonet** [comment]
Can we move this one forward? I need it for the next release.

**Comment by fcamblor** [comment]
Had a look at the whole PR, it sounds good to me except for the `PolymorphicResourceTest` part as it seems like a regression (in behaviour) in jackson to not be able to handle typeinfo in iterables.

I'm wondering if there wouldn't be an `ObjectMapper` configuration somewhere providing back the old behaviour of putting `@class` type info in every iterable's instances, but found nothing in [jackson 2.5 release note](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5) (at least, I isolated the change : on v2.4.6 we had the `@class` type info, and in 2.5.0 we don't have it anymore).

Will try to reach people from Jackson to see if they can help.

**Comment by fcamblor** [comment]
FYI, seems like bug has been confirmed on jackson (see [jackson 1451](https://github.com/FasterXML/jackson-databind/issues/1451))

Bug has been fixed on both 2.7 and 2.8 branches, so I would rather migrate to either 2.7 or 2.8 rather than buggy 2.6.x

I just built locally 2.7.9-SNAPSHOT (including bugfix) and everything is OK in restx with this snapshot version in restx (if we put back json type info in `PolymorphicResourceTest`)

@dadoonet may I ask you to revert `PolymorphicResourceTest` changes and use 2.7.9 instead of 2.6.1 when it will be made available ?
Then, I'll merge the PR :-)

**Comment by fcamblor** [comment]
@dadoonet new version 2.8.6 has been released 3 days ago.

I just tested it and all tests are passing (with reverted `PolymorphicResourceTest`) with this version, so I think it should be OK :)

**Comment by dadoonet** [comment]
So I did the upgrade but when I run the test, I'm still seeing the "regression" in `PolymorphicResourceTest#should_return_B_list`.

I'm getting:

```
[ {
  "a" : "a1"
}, {
  "a" : "a2",
  "b" : "b"
} ]
```

instead of:

```
[ {
  "@class" : ".PolymorphicResource$A",
  "a" : "a1"
}, {
  "@class" : ".PolymorphicResource$B",
  "a" : "a2",
  "b" : "b"
} ]
```

So for now I just updated to 2.8.5. LMK if I missed anything.

**Comment by fcamblor** [comment]
You need 2.8.6, not 2.8.5 :-)

**Comment by dadoonet** [comment]
OMG! I trusted the home page of Jackson project instead of your comment!

**Comment by fcamblor** [comment]
Haha :-D #inBleedingEdgeWeTrust

**Comment by dadoonet** [comment]
Running final tests now. Do you prefer if I squash and rebase on master?

**Comment by dadoonet** [comment]
All good:

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:38 min
[INFO] Finished at: 2017-01-15T18:25:11+01:00
[INFO] Final Memory: 103M/1302M
[INFO] ------------------------------------------------------------------------
```

**Comment by fcamblor** [comment]
```
Running final tests now. Do you prefer if I squash and rebase on master?
```
Yes it would be very nice :-)

**Comment by dadoonet** [comment]
I'm nice then :) 

Done.

**Pull request merged**
